import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { UnderwritingPrecheckRow, PrecheckItem } from "@/hooks/useUnderwritingPrecheck";

function resultLabel(r: string): string {
  switch (r) {
    case "pass": return "PASS";
    case "warning": return "WARNING";
    case "fail": return "FAIL";
    default: return r.toUpperCase();
  }
}

function resultColorRgb(r: string): [number, number, number] {
  switch (r) {
    case "pass": return [34, 139, 34];
    case "warning": return [200, 150, 0];
    case "fail": return [200, 30, 30];
    default: return [100, 100, 100];
  }
}

export function generatePrecheckPdf(
  data: UnderwritingPrecheckRow,
  loanNumber?: string,
  borrowerName?: string,
) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 15;

  // Title
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Underwriting Pre-Check Scorecard", pageWidth / 2, y, { align: "center" });
  y += 10;

  // Loan info
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const infoLines = [
    `Loan: ${loanNumber ?? data.loan_id}`,
    borrowerName ? `Borrower: ${borrowerName}` : null,
    `Date: ${new Date(data.created_at).toLocaleDateString()}`,
    `Overall Result: ${resultLabel(data.overall_result)} (${data.pass_count} pass, ${data.warn_count} warning, ${data.fail_count} fail)`,
  ].filter(Boolean) as string[];

  for (const line of infoLines) {
    doc.text(line, 14, y);
    y += 5;
  }
  y += 3;

  // Overall result banner
  const [r, g, b] = resultColorRgb(data.overall_result);
  doc.setFillColor(r, g, b);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.roundedRect(14, y, pageWidth - 28, 10, 2, 2, "F");
  doc.text(
    data.overall_result === "pass" ? "READY FOR SUBMISSION" : data.overall_result === "warning" ? "REVIEW RECOMMENDED" : "NOT READY — ISSUES FOUND",
    pageWidth / 2,
    y + 7,
    { align: "center" },
  );
  y += 16;

  // Checks table
  doc.setTextColor(0, 0, 0);

  const tableData = (data.checks as PrecheckItem[]).map((check) => [
    check.label,
    resultLabel(check.result),
    check.actual_value,
    check.threshold,
    check.issue_note || "—",
  ]);

  autoTable(doc, {
    startY: y,
    head: [["Check", "Result", "Actual", "Threshold", "Issue Notes"]],
    body: tableData,
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [60, 60, 60], textColor: 255, fontStyle: "bold" },
    columnStyles: {
      0: { cellWidth: 35 },
      1: { cellWidth: 18, halign: "center" },
      2: { cellWidth: 30 },
      3: { cellWidth: 35 },
      4: { cellWidth: "auto" },
    },
    didParseCell: (hookData) => {
      if (hookData.section === "body" && hookData.column.index === 1) {
        const val = hookData.cell.raw as string;
        if (val === "PASS") hookData.cell.styles.textColor = [34, 139, 34];
        else if (val === "WARNING") hookData.cell.styles.textColor = [200, 150, 0];
        else if (val === "FAIL") hookData.cell.styles.textColor = [200, 30, 30];
        hookData.cell.styles.fontStyle = "bold";
      }
    },
  });

  // AI Summary
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = (doc as any).lastAutoTable?.finalY ?? y + 60;
  y += 8;

  if (data.ai_summary) {
    if (y > 260) { doc.addPage(); y = 15; }
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("AI Summary", 14, y);
    y += 6;
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    const summaryLines = doc.splitTextToSize(data.ai_summary, pageWidth - 28);
    doc.text(summaryLines, 14, y);
    y += summaryLines.length * 4 + 4;
  }

  // Remediations
  if (data.ai_remediation?.length > 0) {
    if (y > 240) { doc.addPage(); y = 15; }
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("AI Remediation Notes", 14, y);
    y += 6;

    for (const rem of data.ai_remediation) {
      if (y > 270) { doc.addPage(); y = 15; }
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.text(`${rem.category}:`, 14, y);
      doc.setFont("helvetica", "normal");
      const lines = doc.splitTextToSize(rem.recommendation, pageWidth - 32);
      doc.text(lines, 18, y + 4);
      y += 4 + lines.length * 4 + 2;
      if (rem.guideline_ref) {
        doc.setFontSize(7);
        doc.setTextColor(120, 120, 120);
        doc.text(`Ref: ${rem.guideline_ref}`, 18, y);
        doc.setTextColor(0, 0, 0);
        y += 4;
      }
    }
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by Control Tower · Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 8,
      { align: "center" },
    );
  }

  doc.save(`precheck-${loanNumber ?? data.loan_id}-${new Date().toISOString().split("T")[0]}.pdf`);
}
