-- Action Items: tasks generated by AI agents or created manually.
-- Supports assignment, delegation, and per-user/branch scoping via RLS.

CREATE TABLE IF NOT EXISTS public.action_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  description TEXT,
  assigned_to_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  assigned_by_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  loan_id UUID REFERENCES public.loans(id) ON DELETE SET NULL,
  agent_id UUID REFERENCES public.ai_agents(id) ON DELETE SET NULL,
  source TEXT NOT NULL DEFAULT 'agent',
  priority TEXT NOT NULL DEFAULT 'normal',
  status TEXT NOT NULL DEFAULT 'pending',
  due_date DATE,
  completed_at TIMESTAMPTZ,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.action_items IS 'Tasks generated by AI agents or assigned by users. Supports delegation tracking.';
COMMENT ON COLUMN public.action_items.source IS 'agent | pipeline | email | meeting | document | manual';
COMMENT ON COLUMN public.action_items.priority IS 'high | normal | low';
COMMENT ON COLUMN public.action_items.status IS 'pending | in_progress | completed | cancelled';
COMMENT ON COLUMN public.action_items.assigned_by_user_id IS 'The user who delegated this item. NULL if system/agent-generated.';

CREATE INDEX IF NOT EXISTS idx_action_items_assigned_to ON public.action_items(assigned_to_user_id);
CREATE INDEX IF NOT EXISTS idx_action_items_assigned_by ON public.action_items(assigned_by_user_id);
CREATE INDEX IF NOT EXISTS idx_action_items_loan ON public.action_items(loan_id);
CREATE INDEX IF NOT EXISTS idx_action_items_agent ON public.action_items(agent_id);
CREATE INDEX IF NOT EXISTS idx_action_items_status ON public.action_items(status);
CREATE INDEX IF NOT EXISTS idx_action_items_due_date ON public.action_items(due_date);
CREATE INDEX IF NOT EXISTS idx_action_items_priority ON public.action_items(priority);

DROP TRIGGER IF EXISTS action_items_updated_at ON public.action_items;
CREATE TRIGGER action_items_updated_at
  BEFORE UPDATE ON public.action_items
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- =============================================================================
-- RLS: users see items assigned TO them or assigned BY them (delegation)
-- =============================================================================
ALTER TABLE public.action_items ENABLE ROW LEVEL SECURITY;

-- Admin: full access
CREATE POLICY "action_items_admin_all"
  ON public.action_items FOR ALL
  TO authenticated
  USING (public.has_role('admin'::public.app_role, auth.uid()))
  WITH CHECK (public.has_role('admin'::public.app_role, auth.uid()));

-- Users can SELECT items assigned to them or delegated by them
CREATE POLICY "action_items_select_own"
  ON public.action_items FOR SELECT
  TO authenticated
  USING (
    assigned_to_user_id = auth.uid()
    OR assigned_by_user_id = auth.uid()
  );

-- Users can UPDATE items assigned to them (mark complete, etc.)
CREATE POLICY "action_items_update_assigned"
  ON public.action_items FOR UPDATE
  TO authenticated
  USING (assigned_to_user_id = auth.uid())
  WITH CHECK (assigned_to_user_id = auth.uid());

-- Users who delegated can also update (reassign, cancel)
CREATE POLICY "action_items_update_delegator"
  ON public.action_items FOR UPDATE
  TO authenticated
  USING (assigned_by_user_id = auth.uid())
  WITH CHECK (assigned_by_user_id = auth.uid());

-- Authenticated users can insert (for manual creation or reassignment)
CREATE POLICY "action_items_insert_authenticated"
  ON public.action_items FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Branch Manager: read all action items for loans in their branch
CREATE POLICY "action_items_branch_manager_select"
  ON public.action_items FOR SELECT
  TO authenticated
  USING (
    public.is_branch_manager(auth.uid())
    AND loan_id IS NOT NULL
    AND EXISTS (
      SELECT 1 FROM public.loans l
      WHERE l.id = action_items.loan_id
      AND l.branch_id IS NOT NULL
      AND l.branch_id = public.user_branch_id(auth.uid())
    )
  );
